<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\recursos\Img\Administrador - copia.png" />
    <None Include="wwwroot\recursos\Img\Administrador.png" />
    <None Include="wwwroot\recursos\Img\agendar-cita - copia.png" />
    <None Include="wwwroot\recursos\Img\agendar-cita.png" />
    <None Include="wwwroot\recursos\Img\bola numero 1 - copia.png" />
    <None Include="wwwroot\recursos\Img\bola numero 1.png" />
    <None Include="wwwroot\recursos\Img\bola numero 2 - copia.png" />
    <None Include="wwwroot\recursos\Img\bola numero 2.png" />
    <None Include="wwwroot\recursos\Img\bola numero 3 - copia.png" />
    <None Include="wwwroot\recursos\Img\bola numero 3.png" />
    <None Include="wwwroot\recursos\Img\Bola numero 4 - copia.png" />
    <None Include="wwwroot\recursos\Img\Bola numero 4.png" />
    <None Include="wwwroot\recursos\Img\Buenos Aires - copia.png" />
    <None Include="wwwroot\recursos\Img\Buenos Aires.png" />
    <None Include="wwwroot\recursos\Img\Citas en Línea - copia.png" />
    <None Include="wwwroot\recursos\Img\Citas en Línea.png" />
    <None Include="wwwroot\recursos\Img\Ciudad Mexico - copia.png" />
    <None Include="wwwroot\recursos\Img\Ciudad Mexico.png" />
    <None Include="wwwroot\recursos\Img\configuracion-clinica - copia.png" />
    <None Include="wwwroot\recursos\Img\configuracion-clinica.png" />
    <None Include="wwwroot\recursos\Img\Cuenta de dueño - copia.png" />
    <None Include="wwwroot\recursos\Img\Cuenta de dueño.png" />
    <None Include="wwwroot\recursos\Img\dashboard-usuario - copia.png" />
    <None Include="wwwroot\recursos\Img\dashboard-usuario.png" />
    <None Include="wwwroot\recursos\Img\dashboard-veterinaria - copia.png" />
    <None Include="wwwroot\recursos\Img\dashboard-veterinaria.png" />
    <None Include="wwwroot\recursos\Img\detalle-clinica - copia.png" />
    <None Include="wwwroot\recursos\Img\detalle-clinica.png" />
    <None Include="wwwroot\recursos\Img\Expediente Médico - copia.png" />
    <None Include="wwwroot\recursos\Img\Expediente Médico.png" />
    <None Include="wwwroot\recursos\Img\explorar-clinicas - copia.png" />
    <None Include="wwwroot\recursos\Img\explorar-clinicas.png" />
    <None Include="wwwroot\recursos\Img\Facebook - copia.png" />
    <None Include="wwwroot\recursos\Img\Facebook.png" />
    <None Include="wwwroot\recursos\Img\Facturación - copia.png" />
    <None Include="wwwroot\recursos\Img\Facturación.png" />
    <None Include="wwwroot\recursos\Img\gestion-citas-vet - copia.png" />
    <None Include="wwwroot\recursos\Img\gestion-citas-vet.png" />
    <None Include="wwwroot\recursos\Img\Inicio de sesión - copia.png" />
    <None Include="wwwroot\recursos\Img\Inicio de sesión.png" />
    <None Include="wwwroot\recursos\Img\Instagram - copia.png" />
    <None Include="wwwroot\recursos\Img\Instagram.png" />
    <None Include="wwwroot\recursos\Img\inventario-clinica - copia.png" />
    <None Include="wwwroot\recursos\Img\inventario-clinica.png" />
    <None Include="wwwroot\recursos\Img\Linkedin - copia.png" />
    <None Include="wwwroot\recursos\Img\Linkedin.png" />
    <None Include="wwwroot\recursos\Img\login-page - copia.png" />
    <None Include="wwwroot\recursos\Img\login-page.png" />
    <None Include="wwwroot\recursos\Img\Logo - copia.png" />
    <None Include="wwwroot\recursos\Img\Logo.png" />
    <None Include="wwwroot\recursos\Img\Madrid - copia.png" />
    <None Include="wwwroot\recursos\Img\Madrid.png" />
    <None Include="wwwroot\recursos\Img\mis-mascotas - copia.png" />
    <None Include="wwwroot\recursos\Img\mis-mascotas.png" />
    <None Include="wwwroot\recursos\Img\Multiples sucursale - copia.png" />
    <None Include="wwwroot\recursos\Img\Multiples sucursale.png" />
    <None Include="wwwroot\recursos\Img\NewFile - copia.txt" />
    <None Include="wwwroot\recursos\Img\NewFile.txt" />
    <None Include="wwwroot\recursos\Img\pacientes-expedientes - copia.png" />
    <None Include="wwwroot\recursos\Img\pacientes-expedientes.png" />
    <None Include="wwwroot\recursos\Img\Patitas - copia.png" />
    <None Include="wwwroot\recursos\Img\Patitas.png" />
    <None Include="wwwroot\recursos\Img\pawport-landing-page - copia.png" />
    <None Include="wwwroot\recursos\Img\pawport-landing-page.png" />
    <None Include="wwwroot\recursos\Img\Propietario - copia.png" />
    <None Include="wwwroot\recursos\Img\Propietario.png" />
    <None Include="wwwroot\recursos\Img\Recordatorios - copia.png" />
    <None Include="wwwroot\recursos\Img\Recordatorios.png" />
    <None Include="wwwroot\recursos\Img\Registro Mascotas - copia.png" />
    <None Include="wwwroot\recursos\Img\Registro Mascotas.png" />
    <None Include="wwwroot\recursos\Img\registro-usuario - copia.png" />
    <None Include="wwwroot\recursos\Img\registro-usuario.png" />
    <None Include="wwwroot\recursos\Img\registro-veterinaria - copia.png" />
    <None Include="wwwroot\recursos\Img\registro-veterinaria.png" />
    <None Include="wwwroot\recursos\Img\reportes-clinica - copia.png" />
    <None Include="wwwroot\recursos\Img\reportes-clinica.png" />
    <None Include="wwwroot\recursos\Img\resenas-y-calificaciones - copia.png" />
    <None Include="wwwroot\recursos\Img\resenas-y-calificaciones.png" />
    <None Include="wwwroot\recursos\Img\Twiter or X - copia.png" />
    <None Include="wwwroot\recursos\Img\Twiter or X.png" />
    <None Include="wwwroot\recursos\Img\veterinaria-perro - copia.png" />
    <None Include="wwwroot\recursos\Img\veterinaria-perro.png" />
    <None Include="wwwroot\recursos\Img\Veterinario - copia.png" />
    <None Include="wwwroot\recursos\Img\Veterinario.png" />
  </ItemGroup>

</Project>
